[package]
name = "cogs"
version = "0.1.0"
authors = ["jasoncg"]
edition = "2018"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
crossterm = "0.26.1"
serde = {version = "1.0.163", features = ["derive"]}
serde_yaml = "0.9.21"
sysinfo = "0.29.0"
tui = "0.19.0"
